# Generated by Django 4.1.7 on 2023-03-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReplenishmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('ship_type', models.CharField(choices=[('fast', 'Fast Ship (30 days)'), ('slow', 'Slow Ship (60 days)')], max_length=4)),
                ('cargo_quantity', models.IntegerField()),
                ('cargo_loaded', models.BooleanField(default=False)),
            ],
        ),
    ]
