# Generated by Django 4.1.7 on 2023-03-06 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_sku_asku'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='cargo_quantity',
        ),
        migrations.AddField(
            model_name='ship',
            name='arrival_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ship',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ship',
            name='sku',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='products.sku'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ship',
            name='arrival_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='departure_date',
            field=models.DateField(null=True),
        ),
    ]
