# Generated by Django 4.1.7 on 2023-03-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_remove_ship_cargo_quantity_ship_arrival_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='ship_type',
            field=models.CharField(choices=[('fast', 'Fast Ship (30 days)'), ('slow', 'Slow Ship (60 days)')], max_length=4, null=True),
        ),
    ]
