# Generated by Django 4.1.7 on 2023-03-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_ship_ship_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='cargo_loaded',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
