# Generated by Django 4.1.7 on 2023-03-07 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_sku_asku'),
        ('plans', '0004_ship_remark_alter_ship_cargo_loaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='replenishmentplan',
            name='sku',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='products.sku'),
            preserve_default=False,
        ),
    ]
