# Generated by Django 4.1.7 on 2023-03-07 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_sku_asku'),
        ('plans', '0005_replenishmentplan_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.sku'),
        ),
    ]
