# Generated by Django 4.1.7 on 2023-03-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('asin', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('remark', models.TextField()),
            ],
        ),
    ]
