# Generated by Django 4.1.7 on 2023-03-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='id',
        ),
        migrations.AlterField(
            model_name='sku',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
