# Generated by Django 4.1.7 on 2023-03-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_sku_id_alter_sku_remark_alter_sku_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='asku',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
