# Generated by Django 4.1.7 on 2023-03-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonOrder',
            fields=[
                ('amazon_order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('merchant_order_id', models.CharField(max_length=100)),
                ('purchase_date', models.DateTimeField()),
                ('last_updated_date', models.DateTimeField()),
                ('order_status', models.CharField(max_length=100)),
                ('fulfillment_channel', models.CharField(max_length=100)),
                ('sales_channel', models.CharField(max_length=100)),
                ('order_channel', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('ship_service_level', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=500)),
                ('sku', models.CharField(max_length=100)),
                ('asin', models.CharField(max_length=100)),
                ('item_status', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('currency', models.CharField(max_length=100)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gift_wrap_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gift_wrap_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_promotion_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ship_promotion_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ship_city', models.CharField(max_length=100)),
                ('ship_state', models.CharField(max_length=100)),
                ('ship_postal_code', models.CharField(max_length=100)),
                ('ship_country', models.CharField(max_length=100)),
                ('promotion_ids', models.CharField(max_length=500)),
                ('is_business_order', models.BooleanField(default=False)),
                ('purchase_order_number', models.CharField(max_length=100)),
                ('price_designation', models.CharField(max_length=100)),
                ('customized_url', models.CharField(max_length=500)),
                ('customized_page', models.CharField(max_length=500)),
            ],
        ),
    ]
