# Generated by Django 4.1.7 on 2023-03-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonorder',
            name='gift_wrap_price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='amazonorder',
            name='gift_wrap_tax',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='amazonorder',
            name='item_price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='amazonorder',
            name='item_promotion_discount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='amazonorder',
            name='item_tax',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='amazonorder',
            name='ship_promotion_discount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='amazonorder',
            name='shipping_price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='amazonorder',
            name='shipping_tax',
            field=models.CharField(max_length=100),
        ),
    ]
