# Generated by Django 4.1.7 on 2023-03-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_amazonorder_gift_wrap_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonorder',
            name='is_business_order',
            field=models.CharField(max_length=500),
        ),
    ]
